### ISSUE TITLE
使用问题

### ISSUE THREAD

**Issue by sue-chain** [kaito-kidd/markdown-image-alfred#1]
hello, 使用中发现两个问题：
mac下编辑config.py时候， BUCKET_NAME的英文单引号会一直保存成中文的单引号，用vim直接编辑没问题
zone0,zone1，有个配置选项比较好，如果创建的是七牛华北地区的空间，默认上传就会失败

**Comment by kaito-kidd** [comment]
多谢反馈！老的七牛SDK不支持多地区，现已更新七牛的SDK，重新安装新的workflow即可，感谢反馈！
