### ISSUE TITLE
在使用的时候存在部分问题

### ISSUE THREAD

**Issue by cydiacen** [kaito-kidd/markdown-image-alfred#3]
可以在readme中说明下 需要右键已引入的workflow 然后在Finder中打开 才可以修改对应的配置信息，我一直在源文件的对应文件改了半天，没效果，可能是我太low了，还有配置的外链链接 需要加上http:// 。用是很好用的，谢谢！

**Comment by kaito-kidd** [comment]
安装好插件好，第一次使用快捷键，会自动弹出配置文件的，直接填入即可。
如果没有自动弹出，可以自行找到插件目录填写配置。

**Comment by cydiacen** [comment]
恩 讲道理是这样的 不知道为什么 我引入之后 config.py 里的配置 已经有个默认配置了

**Comment by kaito-kidd** [comment]
非常抱歉，发布的插件包含了调试用的配置，现已更新，重新下载即可。
